title: Akash Rawat # your name (or website title) here
logo: "/images/profile_round.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data scientist with 9 years of experience in Retail, Manufacturing, and Engineering services 
  domains. Skilled in utilizing machine learning, statistical modeling, and data visualization 
  techniques to drive strategic business decisions. Experienced in collaborating with cross 
  functional teams, communicating technical concepts, and delivering actionable insights to stakeholders.
  <br><br>
  <a href="https://www.linkedin.com/in/DSAkashRawat">LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
